### ISSUE TITLE
Sign up for Orpheus Hacks here! ~(aka How to sign up?)~

### ISSUE THREAD

**Issue by hkatzdev** [hackclub/orpheushacks#3]
I didn't see a sign up button on the page, did I miss it? If not how can I sign up? This seems really cool!

**Comment by sampoder** [comment]
I guess we can just use this issue to sign up! I signup!

**Comment by hkatzdev** [comment]
Lol, in that case I also sign up!

**Comment by malteianlauterbach** [comment]
Nonono this is in beta please do not sign upaaaaa

Harrison Katz <notifications@github.com> schrieb am Do., 8. Okt. 2020,
04:47:

**Comment by hkatzdev** [comment]
I would like to register for the beta program, please. I understand that this is not production ready and that if my computer blows up in my face I am liable for all damages and agree to not sue Orpheus.

**Comment by malteianlauterbach** [comment]
There's no beta program. Just wait for the 15th? I think

Harrison Katz <notifications@github.com> schrieb am Do., 8. Okt. 2020,
08:31:

**Comment by hkatzdev** [comment]
~I have switched to a timezone where it is the 15th~
K, going to close this issue then :'(

**Comment by hkatzdev** [comment]
Hello, since today is the 15th can I sign up now? Thanks in advance :P

**Comment by sampoder** [comment]
Agreed, this issue is a matter of the utmost importance.

**Comment by malteianlauterbach** [comment]
did i say 15th? oh no, I'm on holiday :/. If you want to help me speed this up, fix my damn dns entry in hackclub/dns

**Comment by hkatzdev** [comment]
I made a PR but I think it got deleted somehow, I can make it again though

**Comment by hkatzdev** [comment]
Your fork is behind so I'm just gonna make a new fork lol

**Comment by hkatzdev** [comment]
Done - https://github.com/hackclub/dns/pull/399 :)

**Comment by sampoder** [comment]
Sadly we are still being denied the right to sign up, petition to reopen?

**Comment by hkatzdev** [comment]
Agree, CC @lachlanjc

**Comment by lachlanjc** [comment]
Sorry, where do you need me?

**Comment by hkatzdev** [comment]
Could you reopen this issue please? I was assuming that sign ups would open soon after I made the DNS entry, but that wasn't the case so this is an open issue.

**Comment by Muirrum** [comment]
Sign-ups have opened! See #announcements in the Slack.
